version: '3.8'

# Ce fichier est un point d'entrée pour orchestrer tous les services

services:
  # Services Supabase
  supabase-db:
    extends:
      file: ./supabase/docker-compose.yml
      service: supabase-db
  
  supabase-rest:
    extends:
      file: ./supabase/docker-compose.yml
      service: supabase-rest
    depends_on:
      - supabase-db
  
  supabase-kong:
    extends:
      file: ./supabase/docker-compose.yml
      service: supabase-kong
    depends_on:
      - supabase-rest
  
  supabase-meta:
    extends:
      file: ./supabase/docker-compose.yml
      service: supabase-meta
    depends_on:
      - supabase-db
  
  supabase-studio:
    extends:
      file: ./supabase/docker-compose.yml
      service: supabase-studio
    depends_on:
      - supabase-db
      - supabase-rest
      - supabase-kong
      - supabase-meta
  
  supabase-pgadmin:
    extends:
      file: ./supabase/docker-compose.yml
      service: supabase-pgadmin
    depends_on:
      - supabase-db
  
  # Services Odoo
  odoo-db:
    extends:
      file: ./odoo/docker-compose.yml
      service: odoo-db
  
  odoo-enterprise:
    extends:
      file: ./odoo/docker-compose.yml
      service: odoo-enterprise
    depends_on:
      - odoo-db
  
  # Services Coolify
  coolify:
    extends:
      file: ./coolify/docker-compose.yml
      service: coolify
    depends_on:
      - coolify-db
      - coolify-redis
  
  coolify-db:
    extends:
      file: ./coolify/docker-compose.yml
      service: coolify-db
  
  coolify-redis:
    extends:
      file: ./coolify/docker-compose.yml
      service: coolify-redis

networks:
  # Réseau partagé par tous les services
  app-network:
    driver: bridge
    name: ${NETWORK_NAME:-app-network}

# Utilisation:
# Pour démarrer tous les services:
#   docker-compose up -d
#
# Pour démarrer uniquement Supabase:
#   docker-compose up -d supabase-db supabase-rest supabase-kong supabase-meta supabase-studio supabase-pgadmin
#
# Pour démarrer uniquement Odoo:
#   docker-compose up -d odoo-db odoo-enterprise
#
# Pour démarrer uniquement Coolify:
#   docker-compose up -d coolify coolify-db coolify-redis
